### ISSUE TITLE
NameBasedMapConvention try to map "serialVersionUID"

### ISSUE THREAD

**Issue by kosmonaffft** [erchu/bean-cp#16]
java.lang.IllegalAccessException: Can not set static final java.lang.Long field xyz.kosmonaffft.constructr.entities.Connection.serialVersionUID to java.lang.Long
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[na:1.8.0_111]
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[na:1.8.0_111]
	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77) ~[na:1.8.0_111]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_111]
	at com.github.erchu.beancp.FieldBindingSide.setValue(FieldBindingSide.java:52) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.Binding.setValueAtDestination(Binding.java:116) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.Binding.execute(Binding.java:102) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.MapConventionExecutor.lambda$executeBindings$2(MapConventionExecutor.java:182) ~[beancp-1.0.1.jar:na]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[na:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_111]
	at com.github.erchu.beancp.MapConventionExecutor.executeBindings(MapConventionExecutor.java:181) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.MapConventionExecutor.tryMap(MapConventionExecutor.java:136) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.MapConventionExecutor.map(MapConventionExecutor.java:82) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.DeclarativeMapImpl.useConvention(DeclarativeMapImpl.java:227) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.DeclarativeMapImpl.useConvention(DeclarativeMapImpl.java:30) ~[beancp-1.0.1.jar:na]
	at xyz.kosmonaffft.constructr.rest.ConnectionsRestService.lambda$new$2(ConnectionsRestService.java:66) ~[classes/:na]
	at com.github.erchu.beancp.DeclarativeMapImpl.execute(DeclarativeMapImpl.java:334) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.MapperImpl.mapIfMapperAvailable(MapperImpl.java:178) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.MapperImpl.mapIfMapperAvailable(MapperImpl.java:65) ~[beancp-1.0.1.jar:na]
	at com.github.erchu.beancp.MapperImpl.map(MapperImpl.java:48) ~[beancp-1.0.1.jar:na]
	at xyz.kosmonaffft.constructr.rest.ConnectionsRestService.update(ConnectionsRestService.java:105) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]

**Comment by erchu** [comment]
Please download latest development build (link below) and let me know if it fixes this issue. If yes, then I will publish it into Maven repo1.

http://erchu.github.io/bean-cp/download/development/beancp-1.0.2.jar

**Comment by kosmonaffft** [comment]
Yes, issue is fixed.
Thank you.

**Comment by kosmonaffft** [comment]
Hello again.
What about publishing 1.0.2 to maven?

**Comment by erchu** [comment]
Usually it takes few days

**Comment by erchu** [comment]
Maven repo1 has been updated

https://mvnrepository.com/artifact/com.github.erchu/beancp/1.0.2

**Comment by kosmonaffft** [comment]
Thank you.
